global:
  resolve_timeout: 5m
route:
  receiver: rocketmq-exporter-alarm
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
receivers:
- name: rocketmq-exporter-alarm
  webhook_configs:
  - url: http://192.168.0.123:8060/dingtalk